config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cards#index"
  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :card_name, presence: true
  validates :image, presence: true
  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :expiration, presence: true
  
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ポイントカード' },
    { id: 3, name: 'クーポン' }
  ]

  include ActiveHash::Associations
  has_many :cards
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname, presence: true
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数を両方含む必要があります'}
         
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :move_to_index, except: :index

  def index

  end
  
  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  private
  
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def card_params
    params.require(:card).permit(:card_name, :category_id, :shop, :expiration, :image).merge(user_id: current_user.id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.erb
<%= link_to 'POINTCARDを追加', new_card_path, class:"card-btn" %>

app/views/cards/new.html.erb
<%= form_with model: @card, html: { method: :post }, local: true do |f| %>
  <div class="card-infomation">
    <div class="card-infomation-inner">
      <div class="card-image">
        <%= f.label :画像 %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
      <div class="card-name">
        <%= f.label :名前 %>
        <%= f.text_field :card_name %>
      </div>
      <div class="card-shop">
        <%= f.label :よく使うお店 %>
        <%= f.text_field :shop %>
      </div>
      <div class="card-category">
        <%= f.label :種類 %>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      </div>
      <div class="card-expiration">
        <%= f.label :有効期限 %>
        <%= raw sprintf(
          f.date_select(
          :expiration,
          use_month_numbers: true,
          prompt:'--',
          start_year: Time.now.year,
          end_year: (Time.now.year + 10),
          date_separator: '%s'),
          "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
      <div class="new-btn">
        <%= f.submit "追加" %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="top-page-header">
      <div class="header-top-content">
        <%= link_to root_path, class:"header-title" do %>
          <div>PointCard</div>
        <% end %>

        <div class="nav">
          <ul class="lists-right">
            <% if user_signed_in? %>
              <li><%= link_to '#', root_path, class:"user_nickname" %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout" %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path, class:"login" %></li>
              <li><%= link_to '新規登録', new_user_registration_path, class:"sign-up" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>